version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=5432

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
